enum ConnectionState {
  NOT_CONNECTED="NOT_CONNECTED",
  CONNECTING="CONNECTING",
  AUTHENTICATING="AUTHENTICATING",
  AUTHENTICATED="AUTHENTICATED",
  DISCONNECTED="DISCONNECTED",
  ERROR="ERROR",
}

export default ConnectionState;
