enum ConnectionState {
  AUTHENTICATED="AUTHENTICATED",
  AUTHENTICATING="AUTHENTICATING",
  UNAUTHENTICATED="UNAUTHENTICATED",
  CONNECTING="CONNECTING",
  DISCONNECTED="DISCONNECTED",
  ERROR="ERROR",
}

export default ConnectionState;
